package aruscrm;

import javax.swing.table.DefaultTableModel;
import dao.ClienteDAO;
import modelo.Cliente;
import dao.ServicioDAO;
import modelo.Servicio;
import dao.ContratoDAO;
import modelo.Contrato;
import java.util.List;
import java.time.format.DateTimeFormatter;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author robertosolana
 */

public class VentanaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        cargarClientes();
        cargarServicios();
        cargarContratos();
    }

    private void cargarClientes() {
        DefaultTableModel modelo = (DefaultTableModel) tablaClientes.getModel();
        modelo.setRowCount(0);

        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        ClienteDAO dao = new ClienteDAO();
        List<Cliente> clientes = dao.listar();

        for (Cliente c : clientes) {
            Object[] fila = new Object[]{
                c.getId(),
                c.getNombre(),
                c.getEmail(),
                c.getTelefono(),
                c.getEmpresa(),
                c.getOrigenLead(),
                c.getFechaAlta() != null ? c.getFechaAlta().format(formato) : ""
            };
            modelo.addRow(fila);
        }
    }

    private void cargarServicios() {
        DefaultTableModel modelo = (DefaultTableModel) tablaServicios.getModel();
        modelo.setRowCount(0);

        ServicioDAO dao = new ServicioDAO();
        List<Servicio> servicios = dao.listar();

        for (Servicio s : servicios) {
            Object[] fila = new Object[]{
                s.getId(),
                s.getNombre(),
                s.getDescripcion(),
                s.getPrecioBase(),
                s.getTipo()
            };
            modelo.addRow(fila);
        }
    }

    private void cargarContratos() {
        DefaultTableModel modelo = (DefaultTableModel) tablaContratos.getModel();
        modelo.setRowCount(0);

        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        ContratoDAO dao = new ContratoDAO();
        List<Contrato> contratos = dao.listar();

        for (Contrato c : contratos) {
            Object[] fila = new Object[]{
                c.getId(),
                c.getNombreCliente(),
                c.getNombreServicio(),
                c.getFechaInicio().format(formato),
                c.getFechaFin() != null ? c.getFechaFin().format(formato) : "",
                c.getEstado(),
                c.getPrecioFinal(),
                c.isFacturado() ? "Sí" : "No",
                c.getNumeroFactura() != null ? c.getNumeroFactura() : ""
            };
            modelo.addRow(fila);
        }
    }

    // Aquí abajo sigue el código autogenerado por NetBeans (initComponents, etc.)
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        btnNuevoCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        btnRefrescarCliente = new javax.swing.JButton();
        btnEditarCliente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaServicios = new javax.swing.JTable();
        btnNuevoServicio = new javax.swing.JButton();
        btnEliminarServicio = new javax.swing.JButton();
        btnRefrescarServicio = new javax.swing.JButton();
        btnEditarServicio = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaContratos = new javax.swing.JTable();
        btnNuevoContrato = new javax.swing.JButton();
        btnEliminarContrato = new javax.swing.JButton();
        btnRefrescarContrato = new javax.swing.JButton();
        btnEditarContrato = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Email", "Teléfono", "Empresa", "Origen Lead", "Fecha Alta"
            }
        ));
        jScrollPane1.setViewportView(tablaClientes);

        btnNuevoCliente.setText("Nuevo Cliente");
        btnNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoClienteActionPerformed(evt);
            }
        });

        btnEliminarCliente.setText("Eliminar Cliente");
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });

        btnRefrescarCliente.setText("Refrescar");
        btnRefrescarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarClienteActionPerformed(evt);
            }
        });

        btnEditarCliente.setText("Editar Cliente");
        btnEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnEditarCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefrescarCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addComponent(btnNuevoCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNuevoCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRefrescarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditarCliente)
                .addGap(0, 45, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Clientes", jPanel1);

        tablaServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Descripción", "Precio Base", "Tipo"
            }
        ));
        jScrollPane2.setViewportView(tablaServicios);

        btnNuevoServicio.setText("Nuevo Servicio");
        btnNuevoServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoServicioActionPerformed(evt);
            }
        });

        btnEliminarServicio.setText("Eliminar Servicio");
        btnEliminarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarServicioActionPerformed(evt);
            }
        });

        btnRefrescarServicio.setText("Refrescar");
        btnRefrescarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarServicioActionPerformed(evt);
            }
        });

        btnEditarServicio.setText("Editar Servicio");
        btnEditarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarServicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnNuevoServicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarServicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addComponent(btnRefrescarServicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditarServicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(45, 45, 45))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNuevoServicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarServicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRefrescarServicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditarServicio)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Servicios", jPanel2);

        tablaContratos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Servicio", "Fecha inicio", "Fecha fin", "Estado", "Precio final", "Facturado", "Nº Factura"
            }
        ));
        jScrollPane3.setViewportView(tablaContratos);

        btnNuevoContrato.setText("Nuevo Contrato");
        btnNuevoContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoContratoActionPerformed(evt);
            }
        });

        btnEliminarContrato.setText("Eliminar Contrato");
        btnEliminarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarContratoActionPerformed(evt);
            }
        });

        btnRefrescarContrato.setText("Refrescar");
        btnRefrescarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarContratoActionPerformed(evt);
            }
        });

        btnEditarContrato.setText("Editar Contrato");
        btnEditarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarContratoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnNuevoContrato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditarContrato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefrescarContrato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarContrato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(45, 45, 45))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNuevoContrato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarContrato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRefrescarContrato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditarContrato)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Contratos", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarServicioActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tablaServicios.getSelectedRow();

        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Selecciona un servicio de la tabla antes de editar.",
                    "Ningún servicio seleccionado",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int id = (int) tablaServicios.getValueAt(filaSeleccionada, 0);

        ServicioDAO dao = new ServicioDAO();
        List<Servicio> servicios = dao.listar();

        Servicio servicioSeleccionado = null;
        for (Servicio s : servicios) {
            if (s.getId() == id) {
                servicioSeleccionado = s;
                break;
            }
        }

        if (servicioSeleccionado != null) {
            FormularioServicio form = new FormularioServicio(this, servicioSeleccionado);
            form.setVisible(true);

            if (form.isServicioGuardado()) {
                cargarServicios();
            }
        }
    }//GEN-LAST:event_btnEditarServicioActionPerformed

    private void btnRefrescarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarServicioActionPerformed
        // TODO add your handling code here:
        cargarServicios();
    }//GEN-LAST:event_btnRefrescarServicioActionPerformed

    private void btnEliminarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarServicioActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tablaServicios.getSelectedRow();

        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Selecciona un servicio de la tabla antes de eliminar.",
                    "Ningún servicio seleccionado",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int id = (int) tablaServicios.getValueAt(filaSeleccionada, 0); // columna 0 = ID
        String nombre = (String) tablaServicios.getValueAt(filaSeleccionada, 1); // columna 1 = Nombre

        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Seguro que quieres eliminar el servicio \"" + nombre + "\"?",
                "Confirmar eliminación",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE);

        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            ServicioDAO dao = new ServicioDAO();
            dao.eliminar(id);
            cargarServicios(); // refrescamos la tabla tras eliminar
        }
    }//GEN-LAST:event_btnEliminarServicioActionPerformed

    private void btnNuevoServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoServicioActionPerformed
        // TODO add your handling code here:
        FormularioServicio form = new FormularioServicio(this);
        form.setVisible(true);

        if (form.isServicioGuardado()) {
            cargarServicios(); // refrescamos la tabla si se guardó un cliente nuevo
        }
    }//GEN-LAST:event_btnNuevoServicioActionPerformed

    private void btnEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarClienteActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tablaClientes.getSelectedRow();

        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Selecciona un cliente de la tabla antes de editar.",
                    "Ningún cliente seleccionado",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int id = (int) tablaClientes.getValueAt(filaSeleccionada, 0);

        ClienteDAO dao = new ClienteDAO();
        List<Cliente> clientes = dao.listar();

        Cliente clienteSeleccionado = null;
        for (Cliente c : clientes) {
            if (c.getId() == id) {
                clienteSeleccionado = c;
                break;
            }
        }

        if (clienteSeleccionado != null) {
            FormularioCliente form = new FormularioCliente(this, clienteSeleccionado);
            form.setVisible(true);

            if (form.isClienteGuardado()) {
                cargarClientes();
            }
        }
    }//GEN-LAST:event_btnEditarClienteActionPerformed

    private void btnRefrescarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarClienteActionPerformed
        // TODO add your handling code here:
        cargarClientes();
    }//GEN-LAST:event_btnRefrescarClienteActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tablaClientes.getSelectedRow();

        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Selecciona un cliente de la tabla antes de eliminar.",
                    "Ningún cliente seleccionado",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int id = (int) tablaClientes.getValueAt(filaSeleccionada, 0); // columna 0 = ID
        String nombre = (String) tablaClientes.getValueAt(filaSeleccionada, 1); // columna 1 = Nombre

        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Seguro que quieres eliminar al cliente \"" + nombre + "\"?",
                "Confirmar eliminación",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE);

        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            ClienteDAO dao = new ClienteDAO();
            dao.eliminar(id);
            cargarClientes(); // refrescamos la tabla tras eliminar
        }
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClienteActionPerformed
        // TODO add your handling code here:
        FormularioCliente form = new FormularioCliente(this);
        form.setVisible(true);

        if (form.isClienteGuardado()) {
            cargarClientes(); // refrescamos la tabla si se guardó un cliente nuevo
        }
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    private void btnEliminarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarContratoActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tablaContratos.getSelectedRow();

        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Selecciona un contrato de la tabla antes de eliminar.",
                    "Ningún contrato seleccionado",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int id = (int) tablaContratos.getValueAt(filaSeleccionada, 0); // columna 0 = ID
        String cliente = (String) tablaContratos.getValueAt(filaSeleccionada, 1); // columna 1 = Cliente
        String servicio = (String) tablaContratos.getValueAt(filaSeleccionada, 2); // columna 2 = Servicio

        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Seguro que quieres eliminar el contrato de \"" + cliente + "\" con el servicio \"" + servicio + "\"?",
                "Confirmar eliminación",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE);

        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            ContratoDAO dao = new ContratoDAO();
            dao.eliminar(id);
            cargarContratos();
        }
    }//GEN-LAST:event_btnEliminarContratoActionPerformed

    private void btnRefrescarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarContratoActionPerformed
        // TODO add your handling code here:
        cargarContratos();
    }//GEN-LAST:event_btnRefrescarContratoActionPerformed

    private void btnNuevoContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoContratoActionPerformed
        // TODO add your handling code here:
        FormularioContrato form = new FormularioContrato(this);
        form.setVisible(true);

        if (form.isContratoGuardado()) {
            cargarContratos();
        }
    }//GEN-LAST:event_btnNuevoContratoActionPerformed

    private void btnEditarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarContratoActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tablaContratos.getSelectedRow();

        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Selecciona un contrato de la tabla antes de editar.",
                    "Ningún contrato seleccionado",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int id = (int) tablaContratos.getValueAt(filaSeleccionada, 0);

        ContratoDAO dao = new ContratoDAO();
        List<Contrato> contratos = dao.listar();

        Contrato contratoSeleccionado = null;
        for (Contrato c : contratos) {
            if (c.getId() == id) {
                contratoSeleccionado = c;
                break;
            }
        }

        if (contratoSeleccionado != null) {
            FormularioContrato form = new FormularioContrato(this, contratoSeleccionado);
            form.setVisible(true);

            if (form.isContratoGuardado()) {
                cargarContratos();
            }
        }
    }//GEN-LAST:event_btnEditarContratoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarCliente;
    private javax.swing.JButton btnEditarContrato;
    private javax.swing.JButton btnEditarServicio;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnEliminarContrato;
    private javax.swing.JButton btnEliminarServicio;
    private javax.swing.JButton btnNuevoCliente;
    private javax.swing.JButton btnNuevoContrato;
    private javax.swing.JButton btnNuevoServicio;
    private javax.swing.JButton btnRefrescarCliente;
    private javax.swing.JButton btnRefrescarContrato;
    private javax.swing.JButton btnRefrescarServicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTable tablaContratos;
    private javax.swing.JTable tablaServicios;
    // End of variables declaration//GEN-END:variables
}
